[raytracing]
samples = 500
depth = 10
height = 720

[camera]
lookfrom = [0.0, 0.6, 1.0]
lookat = [0.0, 0.0, -1.0]
up_vector = [0.0, 1.0, 0.0]
aperture = 0.01
fov = 72.0
aspect_ratio = 1.0
background_color = [0.5, 0.7, 0.9]

[[materials]]
id = "ground"
type = "lambertian"
color = [0.2, 0.8, 0.2]

[[materials]]
id = "blue"
type = "lambertian"
color = [0.05, 0.05, 0.9]

[[objects]]
id = "ground"
material = "ground"
geometry = "plane"
position = [0.0, -0.5, 0.0]
normal = [0.0, 1.0, 0.0]

[[objects]]
id = "ball"
material = "blue"
geometry = "sphere"
position = [0.0, 0.0, -1.0]
radius = 0.5